SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE ht_congthuc_thanhphan;
TRUNCATE TABLE ht_thanhphan;
TRUNCATE TABLE ht_congthuc;

TRUNCATE TABLE ht_donhang;
TRUNCATE TABLE ht_phieu;
TRUNCATE TABLE ht_me;

TRUNCATE TABLE pm_activities;

SET FOREIGN_KEY_CHECKS = 1;
